DILATE_VECTOR = (6,3)
DILATE_ITERATIONS = 2

MINIMUM_CONTOUR_AREA = 40
SKYLINE = 250
CREDIBLE_HISTORY_LENGTH = 20
CLOSE_NEIGHBOURHOOD = 5
MAX_DEVIATION = 0.05
MAX_FRAME_DIFFERENCE = 15
MAX_DISTANCE = 15
MAX_PREDICTIONS_QUANTITY = 5
BBOX_WIDTH = 10
BBOX_HEIGHT = 20
TEXT_MARIGIN = 10
TEXT_SIZE = 0.4
LINE_WIDTH = 1
WINDOW_NAME = "Pedestrian detection and tracking"
DELIM_WAIT = 40
ESC_PRESSED = 27

VIDEO_PATH = 'D:\krakau.mov'